import {
  Activity,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Bookmark,
  Bot,
  Building2,
  ClipboardList,
  GraduationCap,
  Heart,
  Home,
  LibraryBig,
  ListChecks,
  Newspaper,
  FileCheck2,
  Settings,
  Star,
  Upload,
  Users,
} from 'lucide-react';
import { ROLES } from '../utils/roles.js';

export const menus = {
  [ROLES.STUDENT]: [
    { label: 'Dashboard', path: '/student/dashboard', icon: Home },
    { label: 'Search Books', path: '/search', icon: BookOpen },
    { label: 'Upload Book', path: '/student/upload', icon: Upload },
    { label: 'Submit Book', path: '/student/submissions', icon: FileCheck2 },
    { label: 'My Borrowed Books', path: '/student/borrowed', icon: LibraryBig },
    { label: 'Reading Progress', path: '/student/progress', icon: ListChecks },
    { label: 'Favorites', path: '/student/favorites', icon: Heart },
    { label: 'Bookmarks', path: '/student/bookmarks', icon: Bookmark },
    { label: 'Recommendations', path: '/recommendations', icon: Star },
    { label: 'Notifications', path: '/notifications', icon: Bell },
  ],
  [ROLES.LECTURER]: [
    { label: 'Dashboard', path: '/lecturer/dashboard', icon: Home },
    { label: 'Search Books', path: '/search', icon: BookOpen },
    { label: 'Reading Lists', path: '/lecturer/reading-lists', icon: BookMarked },
    { label: 'Upload Books', path: '/lecturer/uploads', icon: Upload },
    { label: 'Course Resources', path: '/lecturer/resources', icon: GraduationCap },
    { label: 'Student Engagement', path: '/lecturer/engagement', icon: BarChart3 },
    { label: 'Notifications', path: '/notifications', icon: Bell },
  ],
  [ROLES.LIBRARIAN_ADMIN]: [
    { label: 'Dashboard', path: '/admin/dashboard', icon: Home },
    { label: 'Users', path: '/admin/users', icon: Users },
    { label: 'Books', path: '/admin/books', icon: LibraryBig },
    { label: 'Verify Submissions', path: '/admin/book-submissions', icon: FileCheck2 },
    { label: 'Upload Books', path: '/admin/uploads', icon: Upload },
    { label: 'Faculties', path: '/admin/faculties', icon: Building2 },
    { label: 'Borrowing', path: '/admin/borrowing', icon: ClipboardList },
    { label: 'Reviews', path: '/admin/reviews', icon: Star },
    { label: 'Recommendations', path: '/admin/recommendations', icon: Bot },
    { label: 'Analytics', path: '/admin/analytics', icon: BarChart3 },
    { label: 'Reports', path: '/admin/reports', icon: Newspaper },
    { label: 'Activity Logs', path: '/admin/logs', icon: Activity },
    { label: 'Settings', path: '/admin/settings', icon: Settings },
  ],
};
